import { TooltipData } from "@/components/scrap-tooltip";
import { ScrapType } from "@/components/personal-scrap";

export interface LogoScrapData {
  id: string;
  src: string;
  alt: string;
  initialPos: { x: string | number; y: string | number; rotate?: number };
  size?: number;
  tooltipDir?: "right" | "left";
  tooltip: TooltipData;
}

export interface PersonalScrapData {
  id: string;
  src: string;
  alt: string;
  type: ScrapType;
  href?: string;
  tooltip?: TooltipData;
  tooltipDir?: "right" | "left";
  initialPos: { x: string | number; y: string | number; rotate?: number };
  size?: number;
}

export const LOGO_SCRAPS: LogoScrapData[] = [
  {
    id: "aramark",
    src: "/images/experiences/aramark-logo.webp",
    alt: "Aramark",
    initialPos: { x: "60%", y: "20%", rotate: -4 },
    size: 220,
    tooltipDir: "right",
    tooltip: {
      category: "Job",
      title: "Aramark",
      sub: "Building Core Data Infra",
      period: "May 2025 – Present · Philadelphia",
      tags: ["Snowflake", "dbt", "Azure", "Snowpipe"],
      stat: "20M+",
      statLabel: "events/mo",
    },
  },
  {
    id: "npr",
    src: "/images/experiences/npr-logo.webp",
    alt: "NPR",
    initialPos: { x: "82%", y: "15%", rotate: 5 },
    size: 200,
    tooltipDir: "left",
    tooltip: {
      category: "Job",
      title: "NPR",
      sub: "Scaling NPR.org",
      period: "Jun – Aug 2022 · Washington DC",
      tags: ["PHP", "HTML5", "Docker", "Kubernetes"],
      stat: "npr.org",
      statLabel: "shipped",
    },
  },
  {
    id: "webstaurantstore",
    src: "/images/experiences/webstaurantstore-logo.webp",
    alt: "WebstaurantStore",
    initialPos: { x: "58%", y: "45%", rotate: -6 },
    size: 220,
    tooltipDir: "right",
    tooltip: {
      category: "Job",
      title: "WebstaurantStore",
      sub: "Automating the test pipeline",
      period: "May 2024 – May 2025 · Remote",
      tags: ["Java", "Selenium", "Azure DevOps", "SQL Server"],
      stat: "-50%",
      statLabel: "QA cycles",
    },
  },
  {
    id: "asu",
    src: "/images/experiences/asu-logo.webp",
    alt: "Arizona State University",
    initialPos: { x: "75%", y: "58%", rotate: 7 },
    size: 200,
    tooltipDir: "left",
    tooltip: {
      category: "Education",
      title: "Arizona State University",
      sub: "B.S. Computer Science",
      period: "Graduated May 2025 · Tempe, AZ",
      tags: ["CS", "Media Arts Minor", "DAAD Scholar"],
      stat: "4.00",
      statLabel: "GPA",
    },
  },
  {
    id: "sunhacks",
    src: "/images/experiences/sunhacks-logo.webp",
    alt: "sunhacks",
    initialPos: { x: "56%", y: "75%", rotate: -5 },
    size: 200,
    tooltipDir: "right",
    tooltip: {
      category: "Leadership",
      title: "sunhacks",
      sub: "Running ASU's biggest hackathon",
      period: "Tempe, AZ",
      tags: ["600 Attendees", "2× YoY Growth", "$40K Budget"],
      stat: "600",
      statLabel: "attendees",
    },
  },
  {
    id: "snowflake",
    src: "/images/experiences/snowflake-logo.webp",
    alt: "Snowflake",
    initialPos: { x: "46%", y: "38%", rotate: -8 },
    size: 85,
    tooltipDir: "right",
    tooltip: {
      category: "Skill",
      title: "Snowflake",
      sub: "Managing 2K+ locations",
      period: "Aramark — current stack",
      tags: ["Streams", "Snowpipe", "Star Schema"],
    },
  },
  {
    id: "dbt",
    src: "/images/experiences/dbt-logo.webp",
    alt: "dbt",
    initialPos: { x: "85%", y: "35%", rotate: 4 },
    size: 85,
    tooltipDir: "left",
    tooltip: {
      category: "Skill",
      title: "Snowflake",
      sub: "Migrated raw SQL → dbt",
      period: "Aramark",
      tags: ["Models", "Tests", "Docs", "Maintainability"],
    },
  },
  {
    id: "eagleeyes",
    src: "/images/experiences/eagleeyes.webp",
    alt: "EagleEyes Search",
    initialPos: { x: "50%", y: "15%", rotate: 2 },
    size: 150,
    tooltipDir: "left",
    tooltip: {
      category: "Job",
      title: "EagleEyes Search",
      sub: "Drone Control Interface",
      period: "Search & Rescue Startup",
      tags: ["Web App", "UI", "Drones"],
    },
  },
  {
    id: "azure",
    src: "/images/experiences/azure-logo.webp",
    alt: "Microsoft Azure",
    initialPos: { x: "70%", y: "14%", rotate: -5 },
    size: 85,
    tooltipDir: "left",
    tooltip: {
      category: "Skill",
      title: "Microsoft Azure",
      sub: "Cloud & Ingestion pipelines",
      period: "Aramark + WebstaurantStore",
      tags: ["Event Grid", "Functions", "DevOps", "Queues"],
    },
  },
  {
    id: "java",
    src: "/images/experiences/java-logo.webp",
    alt: "Java",
    initialPos: { x: "48%", y: "55%", rotate: 9 },
    size: 80,
    tooltipDir: "right",
    tooltip: {
      category: "Skill",
      title: "Java",
      sub: "Test Automation at scale",
      period: "WebstaurantStore",
      tags: ["Selenium Grid", "JUnit", "Parallel Execution"],
      stat: "-50%",
      statLabel: "regression time",
    },
  },
  {
    id: "python",
    src: "/images/experiences/python-logo.webp",
    alt: "Python",
    initialPos: { x: "78%", y: "42%", rotate: 6 },
    size: 80,
    tooltipDir: "left",
    tooltip: {
      category: "Skill",
      title: "Python",
      sub: "Scripting & Pipelines",
      period: "Aramark + HackKit",
      tags: ["pandas", "SQLAlchemy", "automation"],
    },
  },
  {
    id: "docker",
    src: "/images/experiences/docker-logo.webp",
    alt: "Docker",
    initialPos: { x: "48%", y: "85%", rotate: -3 },
    size: 85,
    tooltipDir: "right",
    tooltip: {
      category: "Skill",
      title: "Docker",
      sub: "Containerizing everything",
      period: "NPR · WebstaurantStore · HackKit",
      tags: ["Compose", "Kubernetes", "CI/CD pipelines"],
    },
  },
  {
    id: "mongodb",
    src: "/images/experiences/mongodb-logo.webp",
    alt: "MongoDB",
    initialPos: { x: "90%", y: "65%", rotate: 5 },
    size: 80,
    tooltipDir: "left",
    tooltip: {
      category: "Skill",
      title: "MongoDB",
      sub: "Real-time scoring for 5K+ users",
      period: "Open Source — HackKit",
      tags: ["Schemas", "Aggregation", "HackKit"],
      stat: "5K+",
      statLabel: "participants",
    },
  },
  {
    id: "kubernetes",
    src: "/images/experiences/kubernetes-logo.webp",
    alt: "Kubernetes",
    initialPos: { x: "75%", y: "85%", rotate: 6 },
    size: 80,
    tooltipDir: "left",
    tooltip: {
      category: "Skill",
      title: "Kubernetes",
      sub: "Production Orchestration",
      period: "NPR — Docker/K8s pipelines",
      tags: ["Deployments", "Staged Rollout", "Production"],
    },
  },
  {
    id: "postgresql",
    src: "/images/experiences/postgresql-logo.webp",
    alt: "PostgreSQL",
    initialPos: { x: "88%", y: "84%", rotate: -7 },
    size: 80,
    tooltipDir: "left",
    tooltip: {
      category: "Skill",
      title: "PostgreSQL",
      sub: "Relational Modeling",
      period: "HackKit + general use",
      tags: ["SQL", "Data Modeling", "Analytics"],
    },
  },
];

export const PERSONAL_SCRAPS: PersonalScrapData[] = [
  {
    id: "justateit",
    type: "cutout",
    src: "/images/outside-work/justateit.webp",
    alt: "justateit",
    href: "https://justateit.com/",
    tooltip: {
      category: "Project",
      title: "justateit",
      sub: "tracking specific dishes instead of whole restaurants",
      period: "In Development",
      tags: ["Taste Mapping", "iOS App"],
      stat: "WIP",
      statLabel: "launching soon",
    },
    tooltipDir: "left",
    initialPos: { x: "65%", y: "17%", rotate: -4 },
    size: 200,
  },
  {
    id: "kulfiboba",
    type: "cutout",
    src: "/images/outside-work/kulfiboba.webp",
    alt: "kulfiboba",
    href: "https://kulfiboba.vercel.app/",
    tooltip: {
      category: "Project",
      title: "kulfiboba",
      sub: "recipes without the life stories",
      period: "Active Archive",
      tags: ["Personal", "No-BS Food"],
      stat: "100%",
      statLabel: "signal, no noise",
    },
    tooltipDir: "right",
    initialPos: { x: "56%", y: "40%", rotate: 4 },
    size: 180,
  },
  {
    id: "boxdbuddy",
    type: "cutout",
    src: "/images/outside-work/boxdbuddy.webp",
    alt: "boxdbuddy",
    tooltip: {
      category: "Project",
      title: "boxdbuddy",
      sub: "fixing letterboxd's missing features",
      period: "Chrome Extension",
      tags: ["UI Tweaks", "Filtering"],
    },
    tooltipDir: "left",
    initialPos: { x: "86%", y: "25%", rotate: 5 },
    size: 100,
  },
  {
    id: "wikigraph",
    type: "cutout",
    src: "/images/outside-work/wikigraph.webp",
    alt: "wikigraph",
    tooltip: {
      category: "Project",
      title: "wikigraph",
      sub: "mapping wikipedia rabbit holes",
      period: "Session Tracker",
      tags: ["Data Viz", "Nodes"],
      stat: "∞",
      statLabel: "depth",
    },
    tooltipDir: "right",
    initialPos: { x: "64%", y: "60%", rotate: -6 },
    size: 100,
  },
  {
    id: "portfolio-stack",
    type: "cutout",
    src: "/images/outside-work/portfolio-stack.webp",
    alt: "portfolio versions",
    tooltip: {
      category: "Project",
      title: "this portfolio",
      sub: "third iteration, i spend a lot of time trying new designs",
      period: "2026 Build",
      tags: ["Next.js", "GSAP", "ASCII"],
      stat: "v3",
      statLabel: "you can find the first two on github",
    },
    tooltipDir: "right",
    initialPos: { x: "52%", y: "22%", rotate: 2 },
    size: 180,
  },
  {
    id: "cooking",
    type: "polaroid",
    src: "/images/outside-work/cooking.webp",
    alt: "cooking",
    tooltip: {
      category: "Hobby",
      title: "Cooking",
      sub: "feeding friends and winding down",
      tags: ["Experimentation", "Dinner Parties"],
    },
    tooltipDir: "left",
    initialPos: { x: "68%", y: "42%", rotate: -4 },
    size: 160,
  },
  {
    id: "ektar",
    type: "cutout",
    src: "/images/outside-work/ektar.webp",
    alt: "first few rolls",
    tooltip: {
      category: "Hobby",
      title: "Analog Photography",
      sub: "expensive hobby I just picked up",
      tags: ["Kodak Ektar", "Point & Shoot"],
      stat: "3",
      statLabel: "rolls deep",
    },
    tooltipDir: "right",
    initialPos: { x: "53%", y: "62%", rotate: 4 },
    size: 170,
  },
  {
    id: "backpacking",
    type: "cutout",
    src: "/images/outside-work/backpacking.webp",
    alt: "budget backpacking",
    tooltip: {
      category: "Travel",
      title: "Backpacking",
      sub: "almost got stranded in iceland",
      period: "Budget Travel",
      tags: ["Hostels", "Guatemala"],
      stat: "1",
      statLabel: "near stranding",
    },
    tooltipDir: "left",
    initialPos: { x: "76%", y: "56%", rotate: -5 },
    size: 170,
  },
  {
    id: "gazella",
    type: "cutout",
    src: "/images/outside-work/gazella.webp",
    alt: "gazella",
    tooltip: {
      category: "Volunteer",
      title: "Phila Ship Guild",
      sub: "working on a literal ship",
      period: "Gazella",
      tags: ["Sanding", "Masts", "Sailing"],
      stat: "50",
      statLabel: "hours sanded",
    },
    tooltipDir: "left",
    initialPos: { x: "78%", y: "20%", rotate: 6 },
    size: 180,
  },
  {
    id: "zoo",
    type: "cutout",
    src: "/images/outside-work/zoo.webp",
    alt: "philadelphia zoo",
    tooltip: {
      category: "Volunteer",
      title: "Philadelphia Zoo",
      sub: "cleaning and guiding tours",
      period: "Docent",
      tags: ["Conservation", "Education"],
      stat: "New",
      statLabel: "role",
    },
    tooltipDir: "right",
    initialPos: { x: "58%", y: "82%", rotate: -2 },
    size: 160,
  },
  {
    id: "paws",
    type: "cutout",
    src: "/images/outside-work/paws.webp",
    alt: "paws shelter",
    tooltip: {
      category: "Volunteer",
      title: "PAWS",
      sub: "walking and cleaning",
      period: "Shelter Volunteer",
      tags: ["Dogs", "Cats"],
    },
    tooltipDir: "right",
    initialPos: { x: "71%", y: "80%", rotate: 4 },
    size: 160,
  },
];
